### ISSUE TITLE
About video rotate

### ISSUE THREAD

**Issue by cheukho** [MasayukiSuda/Mp4Composer-android#13]
hi，I have a problem when i using this lib。

My src video is rotate=90，but composer file is alway rotate=0.

I access code，in class Mp4Composer line 173, the output rotate will add src rotate and setting rotate.

I think there's a problem here.

**Comment by MasayukiSuda** [comment]
fixed
https://github.com/MasayukiSuda/Mp4Composer-android/commit/a9a3ee6c53c4c0059c8633eaaf1bcbeec56b2f49
