### ISSUE TITLE
How to reduce 30MB video file to 5MB file without reduce the quality

### ISSUE THREAD

**Issue by savurajkumar** [MasayukiSuda/Mp4Composer-android#16]
How to reduce 30MB video file to 5MB file without reduce the quality.
Will it possible with this library

**Comment by savurajkumar** [comment]
@MasayukiSuda Could you Please let us know will it possible.

**Comment by MasayukiSuda** [comment]
impossible

**Comment by TejrajJadhav** [comment]
Use https://github.com/fishwjy/VideoCompressor
This helps me to reduce the video size
