### ISSUE TITLE
Cannot apply fillMode as PRESERVE_ASPECT_CROP if fillModeCustomItem is null.

### ISSUE THREAD

**Issue by Stortz** [MasayukiSuda/Mp4Composer-android#18]
Hello, 

First I want to thanks for your library.

But I was with some mistakes to apply fillMode as CROP in to decode/encode the video. I have verified that your math should be right when CROP enum was defined, but after more time in debug I saw that in MP4Composer when I have a null fillModeCustomItem it will always set fillMode to FIT otherwise to CUSTOM, so it will never be CROP.

If I change the enum to CROP after that validation, the video will be encoded as well. 

I have made a fork to change that and use it in my project. Should I create a PR to it?

Thanks

**Comment by MasayukiSuda** [comment]
thx !
