### ISSUE TITLE
Null Resolution in GlOverlayFilter

### ISSUE THREAD

**Issue by GabrielMorenoIbarra** [MasayukiSuda/Mp4Composer-android#23]
I am using `ExoPlayerFilter` to show filters and `Mp4Composer` for rendering. Thank you so much for your libraries. They are awesome!

I am trying to insert an image in a video.

The error I get is this:
`Attempt to invoke virtual method 'int com.daasuu.mp4compose.Resolution.width()' on a null object reference`

I have obtained the same error using `GlWatermarkFilter` and using this example class:
```
import android.graphics.Bitmap
import android.graphics.Canvas
import com.daasuu.mp4compose.filter.GlOverlayFilter

class GlSticker(private val bitmap: Bitmap) : GlOverlayFilter() {

    override fun drawCanvas(canvas: Canvas) {
        canvas.drawBitmap(bitmap, 0f, 0f, null)
    }
}
```
Any idea to resolve the null pointer?

**Comment by GabrielMorenoIbarra** [comment]
I guess it is the same error as https://github.com/MasayukiSuda/Mp4Composer-android/issues/1

**Comment by GabrielMorenoIbarra** [comment]
I have seen the problem... It is due to `inputResolution` was not correctly set. The only thing there is to take into account is to ensure this parameter is set.

**Comment by khurana3192** [comment]
@GabrielMorenoIbarra where do we should set this?

**Comment by GabrielMorenoIbarra** [comment]
Hi, @khurana3192. I did a pull request: https://github.com/MasayukiSuda/Mp4Composer-android/pull/24

**Comment by khurana3192** [comment]
Thank @GabrielMorenoIbarra :)
