### ISSUE TITLE
Overlay with changing Bitmap

### ISSUE THREAD

**Issue by Egorkansk** [MasayukiSuda/Mp4Composer-android#26]
Hello! Thank you  for solution! Is your library can to overlay video with transparent layer in size of video frame and change it in time with Canvas?

**Comment by MasayukiSuda** [comment]
Yes. read <a href="https://github.com/MasayukiSuda/Mp4Composer-android/blob/master/mp4compose/src/main/java/com/daasuu/mp4compose/filter/GlOverlayFilter.java">this</a>.

**Comment by Egorkansk** [comment]
Thank you, I will  try to modify this filter

**Comment by MasayukiSuda** [comment]
read <a href="https://github.com/MasayukiSuda/Mp4Composer-android/blob/master/sample/src/main/java/com/daasuu/sample/GlBitmapOverlaySampleFilter.java">sample.</a>

**Comment by SimranChawla1995** [comment]
Hey,thankyou for your library.It's been a great help. Just one problem i encounter - while overlaying logo on video captured by device camera . I'm overlaying logo on top left, it's showing on top right and in opposite direction. This might have something to do with video's resolution. I guess, first you're overlaying the logo then rotating & changing its resolution. Please help how to resolve the issue.
