### ISSUE TITLE
Android 5 encoding error

### ISSUE THREAD

**Issue by Egorkansk** [MasayukiSuda/Mp4Composer-android#27]
hello i wrote working app , but it not work on android 5, 5.1 throws onFailed exception null object, my LOGS:
2075 E     SoftVideoEncoderOMXComponent egor.faceintro     Unsupported pixel format 0x2
09-08 12:45:48.587 1970 2075 E     SoftAVCEnc egor.faceintro                    Error in extractGraphicBuffer
09-08 12:45:48.587 1970 2074 E     ACodec egor.faceintro                        [OMX.google.h264.encoder] ERROR(0x80001001)
09-08 12:45:48.588 1970 2074 E     ACodec egor.faceintro                        signalError(omxError 0x80001001, internalError -2147483648)
09-08 12:45:48.588 1970 2074 E     ACodec egor.faceintro                        [OMX.google.h264.encoder] ERROR(0x80001001)
09-08 12:45:48.588 1970 2074 E     ACodec egor.faceintro                        signalError(omxError 0x80001001, internalError -2147483648)
09-08 12:45:48.588 1970 2073 E     MediaCodec egor.faceintro                    Codec reported err 0x80001001, actionCode 0, while in state 6
09-08 12:45:48.588 1970 2073 E     MediaCodec egor.faceintro                    Codec reported err 0x80001001, actionCode 0, while in state 0
09-08 12:45:48.691 1970 2074 W     GraphicBufferSource egor.faceintro           Dropped back down to Loaded without Executing
09-08 12:45:48.691 1970 2074 D      egor.faceintro                              HostConnection::get() New Host Connection established 0xe310b170, tid 2074
09-08 12:45:48.693 1970 2084 E     MPEG4Writer egor.faceintro                   The number of recorded samples is 0
09-08 12:45:48.693 1970 2084 W     MPEG4Writer egor.faceintro                   0-duration samples found: 1
09-08 12:45:48.693 1970 2084 W     MPEG4Writer egor.faceintro                   0-duration samples found: 1
09-08 12:45:48.693 1970 2084 I     MPEG4Writer egor.faceintro                   Received total/0-length (0/0) buffers and encoded 0 frames. - Video
09-08 12:45:48.693 1970 2085 I     MPEG4Writer egor.faceintro                   Received total/0-length (13/0) buffers and encoded 13 frames. - Audio
09-08 12:45:48.693 1970 2085 I     MPEG4Writer egor.faceintro                   Audio track drift time: 0 us
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Video track stopping
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Video track source stopping
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Video track source stopped
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Video track stopped
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Audio track stopping
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Audio track source stopping
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Audio track source stopped
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Audio track stopped
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Duration from tracks range is [0, 301859] us
09-08 12:45:48.694 1970 2072 D     MPEG4Writer egor.faceintro                   Stopping writer thread
09-08 12:45:48.697 1970 2083 D     MPEG4Writer egor.faceintro                   0 chunks are written in the last batch
09-08 12:45:48.697 1970 2072 D     MPEG4Writer egor.faceintro                   Writer thread stopped
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             Failed to release mediaMuxer.
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             java.lang.IllegalStateException: Failed to stop the muxer
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at android.media.MediaMuxer.nativeStop(Native Method)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at android.media.MediaMuxer.stop(MediaMuxer.java:225)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at android.media.MediaMuxer.release(MediaMuxer.java:345)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:153)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at com.daasuu.mp4compose.composer.Mp4Composer$100000001.run(Mp4Composer.java:197)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-08 12:45:48.705 1970 2072 E     Mp4ComposerEngine egor.faceintro             at java.lang.Thread.run(Thread.java:818)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    java.lang.IllegalStateException
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at com.daasuu.mp4compose.composer.VideoComposer.drainEncoder(VideoComposer.java:207)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at com.daasuu.mp4compose.composer.VideoComposer.stepPipeline(VideoComposer.java:108)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at com.daasuu.mp4compose.composer.Mp4ComposerEngine.runPipelines(Mp4ComposerEngine.java:173)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:124)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at com.daasuu.mp4compose.composer.Mp4Composer$100000001.run(Mp4Composer.java:197)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-08 12:45:48.705 1970 2072 W     System.err egor.faceintro                    at java.lang.Thread.run(Thread.java:818)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           onFailed()
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           java.lang.IllegalStateException
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at com.daasuu.mp4compose.composer.VideoComposer.drainEncoder(VideoComposer.java:207)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at com.daasuu.mp4compose.composer.VideoComposer.stepPipeline(VideoComposer.java:108)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at com.daasuu.mp4compose.composer.Mp4ComposerEngine.runPipelines(Mp4ComposerEngine.java:173)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:124)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at com.daasuu.mp4compose.composer.Mp4Composer$100000001.run(Mp4Composer.java:197)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-08 12:45:48.707 1970 2072 E     mp4 egor.faceintro                           at java.lang.Thread.run(Thread.java:818)
09-08 12:45:49.692 1970 1992 W     EGL_emulation egor.faceintro                 eglSurfaceAttrib not implemented
09-08 12:45:49.692 1970 1992 W     OpenGLRenderer egor.faceintro                Failed to set EGL_SWAP_BEHAVIOR on surface 0xeb922900, error=EGL_SUCCESS
09-08 12:45:51.863 1970 1992 W     EGL_emulation egor.faceintro                 eglSurfaceAttrib not implemented
09-08 12:45:51.863 1970 1992 W     OpenGLRenderer egor.faceintro                Failed to set EGL_SWAP_BEHAVIOR on surface 0xef3632a0, error=EGL_SUCCESS
09-08 12:45:54.042 1970 1992 W     EGL_emulation egor.faceintro                 eglSurfaceAttrib not implemented
09-08 12:45:54.042 1970 1992 W     OpenGLRenderer egor.faceintro                Failed to set EGL_SWAP_BEHAVIOR on surface 0xeb921d60, error=EGL_SUCCESS
09-08 12:45:55.445 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:45:55.595 501 840 D        system                                      HostConnection::get() New Host Connection established 0xdf392cd0, tid 840
09-08 12:45:55.615 569 569 E       EGL_emulation                                tid 569: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-08 12:45:55.848 569 569 E       EGL_emulation                                tid 569: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-08 12:45:55.877 569 569 D       SurfaceFlinger                               setOrientation, mFbdev=0xf708c0c0, mFbDev->setOrientation=0x0, orientation=0
09-08 12:45:55.877 569 569 E       SurfaceFlinger                               setOrientation: can't set orientation
09-08 12:45:55.879 501 791 I       ActivityManager system                       Config changes=480 {1.0 310mcc270mnc en_US ldltr sw384dp w384dp h567dp 320dpi nrml port finger qwerty/v/v dpad/v s.8}
09-08 12:45:55.924 501 501 V       ActivityManager system                       Display changed displayId=0
09-08 12:45:55.927 501 603 I       InputReader system                           Reconfiguring input devices.  changes=0x00000004
09-08 12:45:55.927 501 603 I       InputReader system                           Device reconfigured: id=1, name='Genymotion Virtual Input', size 768x1280, orientation 0, mode 1, display id 0
09-08 12:45:55.930 501 523 W       art system                                   Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder) from ActivityManagerService.java:6438 waiters=0 for 169ms
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              disableMessage: msg_type = 0x10
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_PREVIEW_FRAME
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              **** Currently enabled messages:
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_ERROR
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_FOCUS
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_ZOOM
09-08 12:45:55.952 124 622 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_PREVIEW_METADATA
09-08 12:45:55.952 124 622 V       EmulatedCamera_Camera                        doStopPreview
09-08 12:45:55.952 124 622 V       EmulatedCamera_Device                        stopDeliveringFrames
09-08 12:45:55.952 124 622 V       EmulatedCamera_Device                        stopWorkerThread
09-08 12:45:55.952 124 622 V       EmulatedCamera_Device                        Stopping emulated camera device's worker thread...
09-08 12:45:55.992 926 1107 W      EGL_emulation com.android.launcher3          eglSurfaceAttrib not implemented
09-08 12:45:55.992 926 1107 W      OpenGLRenderer com.android.launcher3         Failed to set EGL_SWAP_BEHAVIOR on surface 0xed2a0e80, error=EGL_SUCCESS
09-08 12:45:56.009 124 622 V       EmulatedCamera_Device                        Emulated camera device's worker thread has been stopped.
09-08 12:45:56.009 124 622 V       EmulatedCamera_GenyDevice                    stopDevice
09-08 12:45:56.011 124 622 V       EmulatedCamera_GenyDevice                    stopDevice: Geny camera device 'front' is stopped
09-08 12:45:56.011 124 622 V       EmulatedCamera_Preview                       stopPreview
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              disableMessage: msg_type = 0x10
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_PREVIEW_FRAME
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              **** Currently enabled messages:
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_ERROR
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_FOCUS
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_ZOOM
09-08 12:45:56.011 124 625 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_PREVIEW_METADATA
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              disableMessage: msg_type = 0xffff
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_ERROR
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_SHUTTER
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_FOCUS
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_ZOOM
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_PREVIEW_FRAME
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_VIDEO_FRAME
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_POSTVIEW_FRAME
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_RAW_IMAGE
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_COMPRESSED_IMAGE
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_RAW_IMAGE_NOTIFY
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              CAMERA_MSG_PREVIEW_METADATA
09-08 12:45:56.012 124 626 V       EmulatedCamera_CallbackNotifier              **** Currently enabled messages:
09-08 12:45:56.012 124 626 V       EmulatedCamera_Camera                        doStopPreview
09-08 12:45:56.012 124 626 V       EmulatedCamera_Camera                        cancelPicture
09-08 12:45:56.012 124 626 V       EmulatedCamera_Camera                        releaseCamera
09-08 12:45:56.012 124 626 V       EmulatedCamera_Camera                        doStopPreview
09-08 12:45:56.012 124 626 V       EmulatedCamera_GenyDevice                    disconnectDevice
09-08 12:45:56.013 124 626 V       EmulatedCamera_GenyDevice                    disconnectDevice: Disonnected from device 'front'
09-08 12:45:56.013 124 626 D                                                    HostConnection::get() New Host Connection established 0xf2d0e2e0, tid 626
09-08 12:45:56.014 124 626 V       EmulatedCamera_Preview                       setPreviewWindow: current: 0xf2f1b1d0 -> new: 0x0
09-08 12:45:56.014 124 626 I       CameraClient                                 Destroying camera 1
09-08 12:45:56.014 124 626 V       EmulatedCamera_Camera                        closeCamera
09-08 12:45:56.014 124 626 V       EmulatedCamera_Camera                        doStopPreview
09-08 12:45:56.014 124 622 D       NuPlayerDriver                               reset(0xf310c280)
09-08 12:45:56.015 124 1996 D      NuPlayerDriver                               notifyResetComplete(0xf310c280)
09-08 12:45:56.017 124 622 D       NuPlayerDriver                               reset(0xf310c1c0)
09-08 12:45:56.017 124 1998 D      NuPlayerDriver                               notifyResetComplete(0xf310c1c0)
09-08 12:45:56.022 659 1174 W      EGL_emulation com.android.systemui           eglSurfaceAttrib not implemented
09-08 12:45:56.022 659 1174 W      OpenGLRenderer com.android.systemui          Failed to set EGL_SWAP_BEHAVIOR on surface 0xef607ee0, error=EGL_SUCCESS
09-08 12:45:56.093 659 1174 W      EGL_emulation com.android.systemui           eglSurfaceAttrib not implemented
09-08 12:45:56.093 659 1174 W      OpenGLRenderer com.android.systemui          Failed to set EGL_SWAP_BEHAVIOR on surface 0xef607f00, error=EGL_SUCCESS
09-08 12:45:56.108 501 528 I       WindowManager system                         Screen frozen for +327ms due to Window{192beb59 u0 NavigationBar}
09-08 12:45:56.145 501 518 I       ActivityManager system                       Killing 958:com.android.printspooler/u0a50 (adj 15): empty #17
09-08 12:45:56.145 501 518 W       libprocessgroup system                       failed to open /acct/uid_10050/pid_958/cgroup.procs: No such file or directory
09-08 12:45:56.168 501 517 W       libprocessgroup system                       failed to open /acct/uid_10050/pid_958/cgroup.procs: No such file or directory
09-08 12:45:56.429 1281 1762 W     EGL_emulation com.aide.ui                    eglSurfaceAttrib not implemented
09-08 12:45:56.429 1281 1762 W     OpenGLRenderer com.aide.ui                   Failed to set EGL_SWAP_BEHAVIOR on surface 0xe017f060, error=EGL_SUCCESS
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{1211eaae V.ED.... ......ID 110,13-239,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{227e03dc V.ED.... ......ID 110,13-160,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{3c34e5ef V.ED.... ......ID 110,13-160,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{17b6204f V.ED.... ......ID 110,13-263,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{66ee8fc V.ED.... ......ID 110,13-223,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{2993f20b V.ED.... ......ID 110,13-414,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{371e2b85 V.ED.... ......ID 110,13-329,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.461 1281 1281 W     View com.aide.ui                             requestLayout() improperly called by android.widget.TextView{16f93dda V.ED.... ......ID 110,13-369,56 #7f0800a7 app:id/filebrowserEntryName} during layout: running second layout pass
09-08 12:45:56.542 1970 1970 W     IInputConnectionWrapper egor.faceintro       showStatusIcon on inactive InputConnection
09-08 12:45:58.188 501 528 I       art system                                   Explicit concurrent mark sweep GC freed 24601(1287KB) AllocSpace objects, 2(672KB) LOS objects, 33% free, 8MB/13MB, paused 380us total 25.980ms
09-08 12:45:58.341 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:45:58.648 1281 1762 W     EGL_emulation com.aide.ui                    eglSurfaceAttrib not implemented
09-08 12:45:58.648 1281 1762 W     OpenGLRenderer com.aide.ui                   Failed to set EGL_SWAP_BEHAVIOR on surface 0xdbde90c0, error=EGL_SUCCESS
09-08 12:45:59.084 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:45:59.325 501 518 W       InputMethodManagerService system             Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3ef4d27c attribute=null, token = android.os.BinderProxy@242f22ca
09-08 12:45:59.805 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:46:00.115 1281 1762 W     EGL_emulation com.aide.ui                    eglSurfaceAttrib not implemented
09-08 12:46:00.115 1281 1762 W     OpenGLRenderer com.aide.ui                   Failed to set EGL_SWAP_BEHAVIOR on surface 0xe0886520, error=EGL_SUCCESS
09-08 12:46:01.067 1970 1982 D     MPEG4Writer egor.faceintro                   Video track stopping
09-08 12:46:01.067 1970 1982 D     MPEG4Writer egor.faceintro                   Audio track stopping
09-08 12:46:01.067 1970 1982 D      egor.faceintro                              HostConnection::get() New Host Connection established 0xe3e0bdf0, tid 1982
09-08 12:46:01.288 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:46:01.385 1281 1762 W     EGL_emulation com.aide.ui                    eglSurfaceAttrib not implemented
09-08 12:46:01.385 1281 1762 W     OpenGLRenderer com.aide.ui                   Failed to set EGL_SWAP_BEHAVIOR on surface 0xe0886520, error=EGL_SUCCESS
09-08 12:46:01.409 501 915 W       InputMethodManagerService system             Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@1d2f9e81 attribute=null, token = android.os.BinderProxy@242f22ca
09-08 12:46:02.845 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:46:02.896 501 784 W       InputMethodManagerService system             Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@857fb26 attribute=null, token = android.os.BinderProxy@242f22ca
09-08 12:46:03.057 2109 2109 D     AndroidRuntime                               
09-08 12:46:03.057 2109 2109 D     AndroidRuntime                               >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
09-08 12:46:03.059 2109 2109 D     AndroidRuntime                               CheckJNI is OFF
09-08 12:46:03.103 2109 2109 E     memtrack                                     Couldn't load memtrack module (No such file or directory)
09-08 12:46:03.103 2109 2109 E     android.os.Debug                             failed to load memtrack module: -2
09-08 12:46:03.114 2109 2109 D     AndroidRuntime                               Calling main entry com.android.commands.am.Am
09-08 12:46:03.131 2109 2109 D     AndroidRuntime                               Shutting down VM
09-08 12:46:50.612 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:47:03.229 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:47:20.403 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:49:56.825 501 619 W       AudioTrack system                            AUDIO_OUTPUT_FLAG_FAST denied by client
09-08 12:49:57.038 501 619 W

**Comment by MasayukiSuda** [comment]
@creativecoderbee @Egorkansk 
fixed. please try.
