### ISSUE TITLE
failed to instantiate extractor

### ISSUE THREAD

**Issue by sichuanyl** [MasayukiSuda/Mp4Composer-android#29]
void onFailed(Exception exception) get 'failed to instantiate extractor' when first use，and everything is normal next.

**Comment by torindev** [comment]
I have the same issue..

**Comment by MasayukiSuda** [comment]
Please more information.

**Comment by korolevdev** [comment]
![image](https://user-images.githubusercontent.com/7947717/52846607-1ce29480-311b-11e9-9dfa-75facca45eee.png)

**Comment by rsd96** [comment]
I got the same error on a oneplus 5.

**Comment by MasayukiSuda** [comment]
fixed
https://github.com/MasayukiSuda/Mp4Composer-android/commit/9c4edd1c1814d02859df6e1f4ace46342e496fd6
