### ISSUE TITLE
Overlay bitmap on video captured by device camera

### ISSUE THREAD

**Issue by SimranChawla1995** [MasayukiSuda/Mp4Composer-android#33]
Hey,thankyou for your library.It's been a great help. Just one problem i encounter - while overlaying logo on video captured by device camera . I'm overlaying logo on top left, it's showing on top right and in opposite direction. This might have something to do with video's resolution. I guess, first you're overlaying the logo then rotating & changing its resolution. Please help how to resolve the issue.

**Comment by MasayukiSuda** [comment]
use this.
https://github.com/MasayukiSuda/GPUVideo-android

**Comment by SimranChawla1995** [comment]
One problem was with rotation. If video is rotated 90 degree, then logo overlayed at top-left, will come in top-right & if rotated 270 degree,it'll come in bottom-right. I've resolved that issue but another problem was with its resolution since first logo is overlayed & resolution is changing afterwards. So, logo is destorted with changing resolution. I've developed a workaround for that too. Can you please tell me if the above library (GP4Video-android) will resolve these issues  ??

**Comment by MasayukiSuda** [comment]
yes. please try it.
