### ISSUE TITLE
Error on VideoComposer.release()

### ISSUE THREAD

**Issue by alinberce** [MasayukiSuda/Mp4Composer-android#34]
First of all, allow me to thank you for your hard work and making this awesome library. 

What would be the reason for crashing with illegal state exception on ` VideoComposer.release()` , on

Line 146 `if (decoderStarted) decoder.stop();`

or 

Line 151 `if (encoderStarted) encoder.stop();` 

The error comes from Mp4ComposerEngine, line 147
`throw new Error("Could not shutdown mediaExtractor, codecs and mediaMuxer pipeline.", e);`

How to gracefully handle this error in the app?

**Comment by Siddharthflo** [comment]
Hi Alinberce
I am also getting the same error. Any luck resolving the above issue?

**Comment by alinberce** [comment]
The problem still persists...

**Comment by kiku9909** [comment]
i have face this issue while testing on MI devices rest of major devices running well

**Comment by MasayukiSuda** [comment]
fixed
https://github.com/MasayukiSuda/Mp4Composer-android/commit/9c4edd1c1814d02859df6e1f4ace46342e496fd6

**Comment by BilalAsif25** [comment]
@MasayukiSuda @alinberce @Siddharthflo @kikusourabh  

hi guys, any fix for this i am stuck at this, i am using vivo 1915
