### ISSUE TITLE
Any plans to merge your filtering version with mp4composer?

### ISSUE THREAD

**Issue by keremkusmezer** [MasayukiSuda/Mp4Composer-android#37]
Hi,

Are there any plans to merge mp4 composer with your filter supporting version and merge also the exoplayer filters into the same project. I am using all of them together and there are some fixes done on MP4Composer with are totally missing from your fork?

Regards

**Comment by MasayukiSuda** [comment]
I am planning to release it next month.

**Comment by MasayukiSuda** [comment]
use this.
https://github.com/MasayukiSuda/GPUVideo-android
