### ISSUE TITLE
Could not use on API level 16 or below

### ISSUE THREAD

**Issue by ghorbanzadeh-me** [MasayukiSuda/Mp4Composer-android#39]
Is there any way to use this lib in API level 18 And lower ?

I am facing this issue :
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.github.MasayukiSuda:Mp4Composer-android:v0.1.9] /home/emir/.gradle/caches/transforms-1/files-1.1/Mp4Composer-android-v0.1.9.aar/801bab196cd1e1e62921fc80fb8b12c3/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.daasuu.mp4compose" to force usage (may lead to runtime failures)

**Comment by MasayukiSuda** [comment]
read this
https://stackoverflow.com/questions/27095077/how-do-i-use-toolsoverridelibrary-in-a-build-gradle-file
