### ISSUE TITLE
Padding color when using FillMode.PRESERVE_ASPECT_FIT

### ISSUE THREAD

**Issue by dennywahyu** [MasayukiSuda/Mp4Composer-android#45]
Hi. Thank you so much for the library. 
When i use `FillMode.PRESERVE_ASPECT_FIT` to "force" the library to compose a square video with `.size(outputHeight, outputHeight)`, the resulting video will have paddings (on the top&bottom / left&right) just like what i expected. But, the padding was black. How can i change the color of those paddings?

**Comment by MasayukiSuda** [comment]
Yes. Please set GlFilter.class which set the color by setClearColor method.

https://github.com/MasayukiSuda/Mp4Composer-android/blob/master/mp4compose/src/main/java/com/daasuu/mp4compose/filter/GlFilter.java#L170-L175

**Comment by dennywahyu** [comment]
@MasayukiSuda Thanks a lot. It works like a charm.
