### ISSUE TITLE
Support SAF on Android 10

### ISSUE THREAD

**Issue by kimcy929** [MasayukiSuda/Mp4Composer-android#48]
Currently, Android 10 limited access storage. Can you support constructors instead of File.path? Thanks!
```
Mp4Composer(srcFileDescriptor, destFileDescriptor)
Mp4Composer(srcUri, destUri) 
Mp4Composer(scrFilePath, destUri) 
Mp4Composer(scrFilePath, destFileDescriptor) 
```

https://developer.android.com/reference/android/media/MediaMuxer#MediaMuxer(java.io.FileDescriptor,%20int)

**Comment by MasayukiSuda** [comment]
fix this.
https://github.com/MasayukiSuda/Mp4Composer-android/pull/50
