### ISSUE TITLE
Suggestion: Apply multiple filters in chain

### ISSUE THREAD

**Issue by cagkanciloglu** [MasayukiSuda/Mp4Composer-android#5]
Hello,
I have a suggestion that I think improve quality of the library. Right now we can only apply one filter. How about we chain them by making the output of one frame to input of another filter?

**Comment by Procurares** [comment]
Hi,
I really like this library and how it works, the only thing i'm missing is the filters groups

**Comment by andressantiago** [comment]
Currently, I fire off another Mp4Composer instance with the next filter I want to apply.

I agree, it would be nice to have a group of alterations on the same instance of composer.

**Comment by MasayukiSuda** [comment]
use this.
https://github.com/MasayukiSuda/GPUVideo-android
