### ISSUE TITLE
Common filters between libraries

### ISSUE THREAD

**Issue by Link184** [MasayukiSuda/Mp4Composer-android#51]
Seems like you use the same GlFilter in another libraries, but they are incompatible because have different package name. It is possible to place all GlFilter children in the same package or maybe in another library?

I meet issues when tried to apply `com.daasuu.gpuv.egl.filter.GlFilter` instead of `com.daasuu.mp4compose.filter.GlFilter`

**Comment by MasayukiSuda** [comment]
Not support
