### ISSUE TITLE
Error when applying effect to a Camera captured video.

### ISSUE THREAD

**Issue by umairinfinitybits** [MasayukiSuda/Mp4Composer-android#57]
Hi there , I hope you're doing fine. I am facing an issue when I try to Apply effect on a video which is captured by camera. I have tested this on Android Emulator with Android version 9.0 and also tested on a real device with Android version 8.1.
I also imported the sample project, and it also has this issue. Kindly test your sample project app with newly recorded video from camera.
Below is the error log :

> E/Mp4ComposerEngine: Could not shutdown mediaExtractor, codecs and mediaMuxer pipeline.
>     java.lang.IllegalStateException
>         at android.media.MediaCodec.native_stop(Native Method)
>         at android.media.MediaCodec.stop(MediaCodec.java:2084)
>         at c.c.a.e.j.c(VideoComposer.java:166)
>         at c.c.a.e.g.a(Mp4ComposerEngine.java:137)
>         at c.c.a.e.f$b.run(Mp4Composer.java:268)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
> E/f: Unable to compose the engine
>     java.lang.IllegalStateException
>         at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
>         at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
>         at c.c.a.e.j.f(VideoComposer.java:227)
>         at c.c.a.e.j.d(VideoComposer.java:122)
>         at c.c.a.e.g.a(Mp4ComposerEngine.java:242)
>         at c.c.a.e.g.a(Mp4ComposerEngine.java:126)
>         at c.c.a.e.f$b.run(Mp4Composer.java:268)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
> E/ProgressBarActivity: onFailed()
>     java.lang.IllegalStateException
>         at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
>         at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
>         at c.c.a.e.j.f(VideoComposer.java:227)
>         at c.c.a.e.j.d(VideoComposer.java:122)
>         at c.c.a.e.g.a(Mp4ComposerEngine.java:242)
>         at c.c.a.e.g.a(Mp4ComposerEngine.java:126)
>         at c.c.a.e.f$b.run(Mp4Composer.java:268)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
>

**Comment by MasayukiSuda** [comment]
What is the device information?  I have tested on pixel, nexus5, and galaxy devices, but there are no issues.

**Comment by sanketk478** [comment]
yes same issue with camera recorded video.
Resolution : 720 * 1080
