### ISSUE TITLE
FillMode center crop does not working 

### ISSUE THREAD

**Issue by asif-ashraf** [MasayukiSuda/Mp4Composer-android#60]
While we set the FilleMode(FillMode.PRESERVE_ASPECT_CROP) it does pick the video from the center I think it is not working correctly because Center crop meaning is to crop the resource from center

**Comment by MasayukiSuda** [comment]
Please provide more specific information. I don't know what you want to do. Perhaps setting the scale or using FillMode.CUSTOM will do what you want.
