### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by krottv** [MasayukiSuda/Mp4Composer-android#69]
Working with a video is verrry slow. I took 4 minute video and cut 4 seconds of it. It took 20 seconds on Galaxy s9+

Utilizing asynchronous api from android 21 may help with that. https://github.com/mstorsjo/android-decodeencodetest/blob/master/src/com/example/decodeencodetest/ExtractDecodeEditEncodeMuxTest.java

**Comment by krottv** [comment]
Or maybe the issue that the whole video is being processed even thou I selected times to trim it. (I assume, not sure)

**Comment by mahsky** [comment]
I try to optimize the speed
#87

**Comment by MasayukiSuda** [comment]
@mahsky 
Thanks !!

**Comment by krottv** [comment]
Thanks a lot
