### ISSUE TITLE
Sample app does not process video on Android 10 

### ISSUE THREAD

**Issue by wsidortsov** [MasayukiSuda/Mp4Composer-android#72]
**Steps to reproduce:**

1. Install the sample app on Android 10 device
2. Grant permissions
3. Hit "Basic Usage" button
4. Pick any video file from the list and hit "START CODEC !!" button

**Expected result:**

Video file is being processed

**Actual result:** 

Mp4Composer.Listener gets an "onFailed()" callback, because the constructor of the FilePathDataSource fails with FileNotFoundException (EACCESS (Permission denied).

**Workaround:**

Add android:requestLegacyExternalStorage="true" to the application tag in the manifest. See https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html for an in-depth discussion.

**Comment by MasayukiSuda** [comment]
thanks!
https://github.com/MasayukiSuda/Mp4Composer-android/commit/bf782b64a6e758181efc1cec5ea499a9c1833cda
