### ISSUE TITLE
Adjust the video to slow

### ISSUE THREAD

**Issue by luych888** [MasayukiSuda/Mp4Composer-android#73]
Dear Masayuki-san,

Thanks for your share!
When I set the timeScale, the video become fast, but no method to set the video slow, can you give me some advice.

Best Regards!
Luther

**Comment by Zarkex** [comment]
Try to make the speed in negative, for example "-20"

**Comment by luych888** [comment]
Dear Zarkex,

Thanks for your replay。

What do you mean about "make the speed in negative"? 
It's set the timeScale to "-20"? I think it's not work, because the minimum value will be set to 1 in the Mp4Composer.java line #280.

Best Regards！
Luther

**Comment by MasayukiSuda** [comment]
https://github.com/MasayukiSuda/Mp4Composer-android/pull/78

**Comment by luych888** [comment]
Dear Masayuki-san,

Thank you very much！

I will test it as soon as possible.

Base Regards!
Yongchun Lu
