### ISSUE TITLE
Content URI support

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [MasayukiSuda/Mp4Composer-android#75]
Does the library support working with content URIs? (instead of file path). Those are also widely used as a way to work with files through file providers.

**Comment by MasayukiSuda** [comment]
yes.

https://github.com/MasayukiSuda/Mp4Composer-android/blob/master/mp4compose/src/main/java/com/daasuu/mp4compose/composer/Mp4Composer.java#L69-L92
