### ISSUE TITLE
Speed up the Mp4Composer work?

### ISSUE THREAD

**Issue by LuigiVampa92** [MasayukiSuda/Mp4Composer-android#79]
Good day. Thanks for the great library! I use Mp4Composer to add watermark on mp4 videos and it works great. 

Is there a way to speed up the conversion time even if it means some quality loss? It's completely ok for me to lose some quality but the speed of work is crucial in my case. I used to try ffmpeg and in ffmpeg I can set a "preset" parameter. When I set "-preset ultrafast" ffmpeg starts to work at least 2-3 times faster. Can I achieve something like this with this library as well?

Thank you

**Comment by MasayukiSuda** [comment]
The most effective way to improve speed is to set mute to true.
