### ISSUE TITLE
Display wrong on surface view.

### ISSUE THREAD

**Issue by xuanmumy** [MasayukiSuda/Mp4Composer-android#8]
Hello Sir, I try to modify your code for showing effect on screen. I am a  layman on gles/opengl。 I just merge your encodersurface.java and decoder.java into a displaysurface. 
I set surface view to fit video aspect ratio when start play .
 for the test video , it is width 996 height 1328 on screen.
the test video is recorded from phone camera which is 640*480 rotation 90. 
after getScaleAspectFit.  returned scale on x and y are both 1.0, 
but on screen display, video filled good at x demension. but at y demension, it is narrowed, and display in a square  aspect ratio.
I try to increase scale value on y demension, but it is cuted on the top. 
could you tell me how to solve it? why convert video in background is good. do I need to use custom fill mode to scale and translate y direction? how  to determine the scale factor?

**Comment by MasayukiSuda** [comment]
See <a href="https://developer.android.com/reference/android/media/MediaCodec.html">MediaCodec</a>
