### ISSUE TITLE
Convert Image to Video fail 

### ISSUE THREAD

**Issue by AndersonCrew** [MasayukiSuda/Mp4Composer-android#81]
if I set size = Size(1315, 640) => fail with error message : Error 0xfffffc0e
(this is size of image, if I don't set size, => success, I don't know white), Please help me!
Which size do you support to me to convert Image to Video?

**Comment by tapos-datta** [comment]
I think this library can't able to convert image to video properly. Basically it deals with videos.
Using another way you can achieve the result that is considering a dummy video with applying a GlBitmapOverlaySampleFilter of the input image.
